# Generated by Django 5.2.8 on 2025-11-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_text',
            field=models.TextField(blank=True, null=True, verbose_name='نص الفوتر'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='شعار الموقع'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='VogaStyle', max_length=100, verbose_name='اسم الموقع'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
