# Generated by Django 5.2.8 on 2025-11-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'بانر',
                'verbose_name_plural': 'البانرات',
            },
        ),
        migrations.CreateModel(
            name='FeaturedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='collections/')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'كولكشن مميز',
                'verbose_name_plural': 'كولكشنز مميزة',
            },
        ),
    ]
