# Generated by Django 5.2.8 on 2025-11-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رابط الزر'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نص الزر'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='صورة البانر'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط؟'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='العنوان الفرعي'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان البانر'),
        ),
        migrations.AlterField(
            model_name='featuredcollection',
            name='image',
            field=models.ImageField(upload_to='collections/', verbose_name='صورة الكولكشن'),
        ),
        migrations.AlterField(
            model_name='featuredcollection',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='featuredcollection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الكولكشن'),
        ),
    ]
